<?php
// language specific strings for use in Oval Office

// syntax: define('VAR', 'value');
/*
define('','');
define('','');
define('','');
define('','');
define('','');
define('','');
*/

define('GAME_ICON_SERVER','http://data.zombinoia.com/gfx/icons/item_');
define('GAMESERVER_ITEM','http://data.zombinoia.com/gfx/icons/item_');
define('GAMESERVER_TAG','http://data.zombinoia.com/gfx/icons/tag_');
define('GAMESERVER_ICON','http://data.zombinoia.com/gfx/icons/');
define('GAMESERVER_SMILEY','http://www.zombinoia.com/gfx/forum/smiley/');

define('DATETIME_FULL', '%e. %B %Y | %H:%M');
define('DATETIME_MINI', '%e.%m.%Y, %H:%M');

# global
define('VERSION','version');
define('MAINTENANCE_MSG','Hay algunos zombies entrando, por favor, espera hasta que lo resolvamos.');
define('ERROR_CODE', 'error de código');
define('ERROR_XML_DEFAULT', 'error de XML');
define('CATEGORY','categoría');
define('ITEM','objeto');
define('DAY','día');
define('DAYS','días');
define('DAYS_DATIV','días');
define('STATUS_QUO','Estado actual');
define('TIME_APPENDIX','');
define('CAUTION', 'Precaución');
define('AMP','&');
define('NOTE','Nota');
define('PRESET_SAVE', 'Guardar ajuste');
define('PRESET_LOAD', 'Cargar ajuste');
define('PRESET_SAVED', 'Ajuste guardado.');
define('PRESET_LOADED', 'Ajuste cargado.');
define('ERROR_OCCURED', 'Ha ocurrido un error.');
define('COUNT', 'número');
define('AMOUNT', 'cantidad');
define('ENTER_VALUES', 'Enviar');
define('NAME', 'Nombre');
define('LOCATION', 'Localización');
define('DEATHCAUSE', 'Causa de la muerte');
define('SEASON','Temporada');
// jobs
define('RESIDENT', 'ciudadano');
define('CITIZEN', 'habitante');
define('CITIZEN_NOJOB', 'sin empleo');
define('HERO','Héroe');
define('HEROS','Héroes');
define('SCAVENGER', 'Excavador');
define('SCOUT', 'Explorador');
define('TAMER', 'Domador');
define('GUARDIAN', 'Guardián');
define('HUNTER', 'Ermitaño');
define('TECH', 'Técnico');
define('SHAMAN', 'Chamán');
define('DEAD_CITIZEN', 'muerto');
define('DEADS','muerto');
define('BANNED','desterrado');
define('AP', 'PA');
define('CP', 'CP');
define('KM', 'km');
// city and directions
define('CITY', 'Ciudad');
define('Nx','Norte');
define('Wx','Oeste');
define('Sx','Sur');
define('Ex','Este');
define('NEx','Noreste');
define('NWx','Noroeste');
define('SEx','Sureste');
define('SWx','Suroeste');
define('N','N');
define('W','O');
define('S','S');
define('E','E');
define('NE','NE');
define('NW','NO');
define('SE','SE');
define('SW','SO');
define('ZOMBIE', 'zombie');
define('ZOMBIES', 'zombies');
define('ZOMBIEX','%s');
define('EXISTENT','disponible');
define('TODAY','hoy');
define('YESTERDAY','ayer');
define('APPROXY','aprox.');
define('DEFOE_TOWN','Ciudades normales');
define('HARD_TOWN','Pandemonio');
define('ATTACK_TODAY','Cálculo del ataque de hoy:');
define('ATTACK_TOMORROW','Cálculo del ataque de mañana');
define('CITIZENS_OUTSIDE','ciudadanos fuera');

define('FOYER_INTRO','Introducción');
define('FOYER_ID','Identificación');
define('FOYER_GM','Complementos & Scripts');

define('ISSUED_AT','Emitido desde');
define('ON','el');
define('CURRENT_SOUL_POINTS','Puntos de alma actuales');
define('CURRENT_CLEAN_POINTS','Puntos de limpio actuales');
define('CODE_EXPLAIN','Tu código de acceso seguro es <em>%c</em>. <strong style="color:#633;">¡NUNCA COMPARTAS ESTE CÓDIGO CON NADIE!</strong><br/>Añade <a style="color:#633;" href="http://zombinoia.net/ovaloffice/?key=%c">este enlace</a> a tu barra de marcadores para tener acceso inmediato al Oval Office sin necesidad de pasar antes por Zombinoia.
<div class="error">NOTA: Si desactivas la casilla que te permite utilizar aplicaciones externas en tu alma y vuelves a activarla, un <strong>nuevo código</strong> será generado y el enlace de marcadores no seguirá funcionando. Entonces tendrás que volver a visitar el Oval Office a través de Zombinoia una vez. Realmente deberías hacer eso para poder cambiar tu código.');
define('TOWN_OVERVIEW','Panorama del pueblo');

# mail
define('YOUR_MAILBOX', 'Mensajería Oval');
define('YOUR_MESSAGES', 'Tus mensajes');
define('YOUR_FRIENDS', 'Tus contactos');
define('INVITE', 'Invitar');
define('USER_NOT_YET_LOGGED_IN', 'Este usuario no ha entrado aún.');
define('USER_UNKNOWN', 'Nombre de usuario desconocido.');
define('USER_IGNORES_YOU', 'Este usuario no quiere que le contactes.');
define('USER_INVITED_YOU', 'Este usuario te envió una invitación. Por favor, responde a la petición.');
define('USER_ALREADY_INVITED', 'Ya has invitado a este usuario, espera su respuesta.');
define('USER_INVITED','Invitaste a %s a ser uno de tus contactos.');
define('USER_NOT_YOUR_FRIEND','Este usuario aún no está en tu lista de contactos.');
define('PENDING','Pendiente');
define('INVITES', 'Invitaciones');
define('ACTIVE_CONTACTS','Amigos');
define('ACCEPT_REQUEST','Aceptar invitación');
define('DECLINE_REQUEST','Rechazar invitación');
define('IGNORE_REQUEST','Ignorar usuario');
define('SEND_MSG', 'Enviar mensaje');
define('MSG_SENT', 'Mensaje enviado.');
define('USER_ACCEPTED', '%s está ahora en tus contactos.');
define('FROM','De');
define('TO','Para');
define('SUBJECT','Tema');
define('TIME_SENT','Enviado');
define('TIME_RECEIVED', 'Recibido');
define('TRASH', 'Borrar');
define('TRASH_MAIL', 'Borrar mensaje');
define('NO_MSGS','No hay mensajes');
define('ANSWER_MSG','Responder');
define('SELFINVITE','Sin amigos reales, ¿eh? Es triste.');
define('USER_DECLINED', 'Has rechazado la invitación de %s.');
define('USER_WITHDRAWN', 'Retiraste la invitación a %s.');
define('USER_DELETED', '%s ya no es uno de tus contactos.');
define('DELETE_CONTACT', 'Borrar contacto');
define('WITHDRAW_INVITE', 'Retirar invitación');

# bank
define('Rsc', 'Recursos');
define('Food', 'Provisiones');
define('Armor', 'Defensas');
define('Drug', 'Farmacia');
define('Weapon', 'Armería');
define('Misc', 'Varios');
define('Furniture', 'Objetos caseros');
define('Box', 'Contenedores y cajas');
define('GRAPH_SETTINGS', 'Configuración gráfica');
define('GRAPH_TYPE', 'Tipo de diagrama');
define('GRAPH_BARS', 'barras');
define('GRAPH_LINES', 'líneas');
define('GRAPH_MAX_VALUES','Máximo nº de grupos');
define('BANK_CONTENT', 'Almacén');
define('BANK_CHANGE_MSG', 'Los números entre paréntesis muestran las diferencias respecto al día anterior.');
define('BROKEN', 'roto');
define('BANK_HISTORY_MSG', 'Un viejo libro contiene dibujos de objetos olvidados.');
define('GRAPH_BANK_TITLE','Cambios con el tiempo');
define('WWATER','Agua (almacén)');
define('WWELL','Agua (pozo)');
define('FOOD','Comida');
define('DRUGS','Drogas');
define('ALCOHOL','Alcohol');
define('COFFEE','Café');

# bauamt
define('CONSTRUCTION_YARD_TITLE','Construcciones de autoridad');
define('SELECT_NONE','No seleccionar nada');
define('SELECT_ALL','Seleccionar todo');
define('SHOW_BPONLY','Enseñar sólo lo disponible');
define('SHOW_ALL','Enseñar todo');
define('GET_CONSTRUCTION_PERMIT','¡Aplicar!');
define('ALREADY_BUILT','¡Ya está construido!');
define('TEMPORARY_BUILDING','Construcción temporal');
define('TEMPORARY','temporal');
define('MARK_AS_BLUEPRINT_FOUND','Marcar este plano como disponible.');
define('MARK_AS_BLUEPRINT_LOST','Marcar este plano como no disponible.');
define('REMAINS','restos');
define('REMAIN','resto');
define('ITEMS_REMAINING', '%d %s.');
define('MISSES','falta');
define('MISS','faltan');
define('ITEMS_MISSING', '%d %s!');
define('CONSTRUCTION_PERMIT_REQUESTED', 'Aplicación para %d construcciones');
define('VP_GAIN', 'El pueblo ganará %s defensas.');
define('WILLS','serán');
define('WILL','será');
define('VP_ITEM','objeto de defensa');
define('VP_ITEMS','objetos de defensa');
define('VP_USE','Sin embargo, %d %t %s se usó.');
define('REQUIRED_RESOURCES','Recursos necesarios');
define('REQUIRED_AP_BUILD','PA requeridos para la construcción');
define('REQUIRED_AP_WORKSHOP','PA requeridos convirtiendo recursos');
define('CONSTRUCTION_PERMIT','PERMISO DE CONSTRUCCIÓN');
define('REQUESTED_BY','emitido por Oval Office en aplicación de %s');
define('CONSTRUCTIONS_PERMITTED','Aprobada(s) %s [g]%d construcción(es)[/g]');
define('HAS_BEEN','');
define('HAVE_BEEN','');
define('WORKSHOP_CONVERSIONS', 'Transformaciones disponibles');
define('REQUIRED_STEPS', '%d pasos requeridos.');
define('FACTORY','Fábrica');
define('SAW','Sierra');
define('EXIST','disponible');
define('PERMIT_COPY_NOTICE', 'Pulsando <span style="font-variant:small-caps;">Ctrl+C</span> podrás copiar este permiso y pegarlo en los foros pulsando <span style="font-variant:small-caps;">Ctrl+V</span>.');

# ema
define('EMA_NONAME', 'Tu nombre no pudo ser leído.');
define('EMA_OFFICE', 'Disponibilidad ciudadana');
define('EMA_REGISTER','Registro de ciudadanos');
define('EMA_OFFICE_TITLE','DAPAPO - Divulgación de asistencia personal asistida por ordenador');
define('EMA_OFFICE_INFO','Para una planificación detallada, por favor, proporciona tu estado actual cada día.');
define('EMA_OFFICE_TUTORIAL','<h4 style="cursor:pointer;" onclick="$(\'.ema-tut\').toggleClass(\'hideme\');"><span style="float:right;font-weight:normal;font-style:italic;">Click para cambiar</span>Tutorial rápido</h4><p class="ema-tut hideme">La intención de estos registros es recoger datos sobre la disponibilidad y el estado de cada ciudadano para los días posteriores. Especialmente para expediciones esto podría ser muy útil para los participantes para ponerse de acuerdo a la hora de comer, beber o tomar drogas durante el camino. También puede ayudar a evaluar la capacidad de alguien para entrar al juego poco antes del ataque y decidir si se pueden o no cerrar las puertas.</p><p class="ema-tut hideme">Puedes establecer tu actual estado (o el que tendrás mañana) que es importante para calcular los PC (esta información también es usada por Travel Agency). Los estados Sediento o Resaca por ejemplo podrían indicar que el ciudadano respectivo debería tomar una ruta más corta o que no podrá tomar alcohol.</p><p class="ema-tut hideme">Tu paquete de almuerzo es esencial para saber cuántos PA tienes disponibles y trazar una ruta.</p><p class="ema-tut hideme">Finalmente, los recuadros de color pueden ser usados para dar información sobre tu conectividad. El rojo sería algo como "Definitivamente no estaré online.", el amarillo se refiere esas veces cuando puedes entrar al juego pero no puedes estar conectado todo de forma continua y el verde significa que puedes estar totalmente activo.</p><p class="ema-tut hideme">Puedes guardar un ajuste representando tus datos más comunes para que no tengas que volver a colocar tus estados y horarios cada día. Cuantos más ciudadanos usen esta función, mejor será el panorama. Los usuarios con problemas de visión de colores pueden cambiar a símbolos usando el enlace debajo del botón Enviar.</p>');
define('EMA_FORM_DAY','Asistencia del día');
define('EMA_S_THIRSTY','sediento');
define('EMA_S_HANGOVER','resaca');
define('EMA_S_TERRORIZED','aterrorizado');
define('EMA_S_CLEAN','limpio');
define('EMA_S_TOPFORM','Héroe: cuerpo sano');
define('EMA_S_SAFE','Héroe: armadura de cristal');
define('EMA_CARE','Tu paquete de almuerzo');
define('EMA_S_WATER','Agua (6 PA)');
define('EMA_S_FOOD_DEFOE','Comida estándar (6 PA)');
define('EMA_S_FOOD_YUMMY','Comida premium (7 PA)');
define('EMA_S_STEROID','Esteroides (6 PA)');
define('EMA_S_TWINOID','Twinoid 500mg (8 PA)');
define('EMA_S_ALCOHOL','Alcohol (6 PA)');
define('EMA_S_COFFEE','Café (4 PA)');
define('EMA_S_ALARM','Reloj de alarma (1 PA)');
define('EMA_S_GAMBLE','Juego de azar (1 PA)');
define('EMA_S_SIESTA','Siesta Time™ (2 PA)');
define('EMA_S_2NDLUNG','Héroe: Segundo aliento (6 PA)');
define('EMA_LIST','Lista de asistencia');
define('EMA_REGISTER_INFO','');
define('DC1','Deshidratado');
define('DC2','Suicidio (admin)');
define('DC3','Suicidio por cianuro');
define('DC4','Ahorcado');
define('DC5','Muerte afuera');
define('DC6','Devorado por zombies en el pueblo');
define('DC7','Retirada');
define('DC8','Infección');
define('DC9','Tiro en la cabeza (cuenta eliminada por un admin)');
define('DC10','Evaporizado (cuenta eliminada)');
define('DC11','Envenenado');
define('DC12','Devorado por un ghoul');
define('DC13','Agresión (ghoul)');
define('DC14','Ghoul hambriento');
define('DC15','Cajita feliz');
define('DC0','causa desconocida');
define('EMA_T_NONE','n/a');
define('EMA_T_NOT','no online');
define('EMA_T_SPORA','esporádicamente online');
define('EMA_T_ACTIV','activamente online');
define('EMA_B_WATER','PA de agua');
define('EMA_B_FOOD','PA de comida');
define('EMA_B_STEROID','PA de esteroides');
define('EMA_B_TWINOID','PA de Twinoid 500mg');
define('EMA_B_ALCOHOL','PA de alcohol');
define('EMA_B_COFFEE','PA de café');
define('EMA_B_ALARM','PA de reloj de alarma');
define('EMA_B_GAMBLE','PA de juegos de azar');
define('EMA_B_SIESTA','PA de Siesta Time™');
define('EMA_B_2NDLUNG','PA de segundo aliento');
define('EMA_TOGGLE_CODES', 'cambiar a colores/símbolos');
define('CADAVER_GARBAGED', 'Tirado fuera del pueblo');
define('CADAVER_SPRINKLED', 'Mojado');
define('BY','por');
define('HOURS','horas');
define('LOC_INTOWN','dentro del pueblo');
define('LOC_ATDOOR','en el Portal');
define('EEO','e. &amp; e.o.');

# map
define('ZONE_D_0','Zona segura');
define('ZONE_D_1','Zombis sueltos');
define('ZONE_D_2','Banda de zombis');
define('ZONE_D_3','Turba de zombis');
define('ZONE_D_4','Lleno de zombies');
define('ZONE_DIG','La ruina tiene que ser despejado <strong>%d</strong> veces.');
define('COORDS','coordenadas');
define('ZONE_DRIED','Esta zona está <strong>agotada</strong>.');
define('BUILDING_DRIED','Esta ruina está <strong>agotada</strong>.');
define('BUILDING_REGENERATED','Esta ruina está <strong>agotada</strong>.');
define('ZONE_DANGER','nivel de peligro');
define('ZONE_NYV','Aún no visitado');
define('ZONE_NVT','No visitado hoy');
define('ZONE_LASTUPDATE','Última actualización');
define('ZONE_LASTVISIT','Última visita');
define('ZONE_LASTRADAR','Último radar');
define('ZONE_ITEMSONGROUND','Objetos en el suelo');
define('MAP_OP_TITLE','Detalles de la zona');
define('MAP_OP_INFO','Información de la zona');
define('MAP_OP_STORM','Tormenta');
define('MAP_OP_SETTINGS','Opciones');
define('MAP_OP_EXPEDITIONS','Expediciones');
define('MAP_LAYER_ZCORI','Zombies (colores ZBN)');
define('MAP_LAYER_ZCDET','Zombies (colores detallados)');
define('MAP_LAYER_CITCOUNT','Ciudadanos');
define('MAP_LAYER_ZOMCOUNT','Cantidad de zombies');
define('MAP_LAYER_ZONEMARKER','Marca de la zona');
define('MAP_LAYER_DIRCOLOR','Direcciones (superpuestas)');
define('MAP_LAYER_DIRBORDER','Direcciones (bordes)');
define('MAP_LAYER_WATCHTOWER','Radio de transporte de la torre');
define('MAP_LAYER_SEARCH','Resultados de búsqueda');
define('MAP_SEARCH_CAT','Escoger categoría o');
define('MAP_SEARCH_ITEM','seleccionar objeto');
define('MAP_SEARCH_FIND','¡Encontrado!');
define('MAP_LEGEND','Leyenda');
define('MAP_ALL_EXPEDITIONS','Todas las expediciones');
define('MAP_SEARCH_TOGGLE_VIEW','Mostrar botón');
define('MAP_SEARCH_TOGGLE_INFO','Cambiar de vista por defecto a la versión para formato de foros');
define('MAP_SEARCH_ITEM_FOUND','%s encontrado en');
define('ZONE_INFO_ASOF','a partir de');
define('MAP_SEARCH_ITEM_NOT_FOUND','Lo sentimos, no encontramos ninguna zona con %s.');
define('MAP_SEARCH_AJAXCOMPLETE','¿Te refieres a ...');
define('MAP_SEARCH_RUNNING','La búsqueda de %s está en proceso ...');
define('MAP_SEARCH_NOTHING_FOUND','No se encontró nada.');
define('MAP_SEARCH_SHORT_TERM','Por favor, introduce al menos tres letras.');
define('ZONE_REGENERATED','La zona se ha repuesto.');
define('ZONE_NEW_REGENERATED','Zona aún no visitada (regenerada).');
define('ZONE_NOT_REGENERATED','La zona <em>no</em> está regenerada.');
define('ZONE_RADAR_INFO','Información de radar de zona');
define('WATCHTOWER','Torre de vigilancia');
define('VISION','Memoria de un ciudadano');
define('MAP_COLOR_BACK','Color de fondo de la zona');
define('NO_BACKCOLOR','Sin color de fondo');
define('MAP_RADIUS','Radio');
define('MAP_INFOLAYER','Info');
define('MAP_SEARCHFORM','Buscar en el mapa');
define('MAP_LAYER_VISITSTATUS','Estado de visita');
define('MAP_LAYER_CITIDOT','Puntos de ciudadano');
define('MAP_LAYER_HUMCOUNT','Cuenta de ciudadano');
define('MAP_LAYER_WATCHTOWER1','Bonus de torre (nivel 4)');
define('MAP_LAYER_WATCHTOWER2','Bonus de torre (nivel 5)');
define('MAP_LAYER_RADIUS6','Radio 6PA');
define('MAP_LAYER_RADIUS9','Radio 9PA');
define('MAP_LAYER_RADIUS15','15km radio');
define('MAP_LAYER_REGENSTATUS','Estado de zona (¿obsoleta?)');
define('MAP_LAYER_REGENERATION','Radar de excavador');
define('LAST_OFFICIAL_COUNT','Última cuenta oficial');
define('EDIT_ZONE_INFO','Editar información de zona');
define('REGISTER_STORM','Registrar tormenta');
define('STORM_LOG','Apunte de tormenta');
define('MAP_DIRECTIONS','Direcciones');
define('SCOUT_INFO','Información de explorador');
define('DESERT','Desierto');
define('M_BUILDING_REGENERATED','Ruina <strong>regenerada</strong>');
define('M_ZONE_REGENERATED','Zona <strong>regenerada</strong>');
define('M_BUILDING_DEPLETED','Ruina <strong>agotada</strong>');
define('M_ZONE_DEPLETED','Zona <strong>agotada</strong>');
define('M_ZONE_DIG','con escombros: <strong>%d</strong>');

# travel
define('Ngo','NORTE (arriba)');
define('Wgo','OESTE (izquierda)');
define('Sgo','SUR (abajo)');
define('Ego','ESTE (derecha)');
define('TRAVEL_TITLE','Travel Agency');
define('TRAVEL_INFO','');
define('TRAVEL_YOUR_GROUP','Tu grupo de viaje');
define('TRAVEL_NO_GROUP','No eres miembro de un grupo de viaje. ¡Crea tú uno!');
define('TRAVEL_GROUP_NAME','Nombre del grupo');
define('TRAVEL_NEW_GROUP_NAME','grupo de trabajo');
define('TRAVEL_GROUP_PERSISTENT','Hacer grupo permanente');
define('TRAVEL_GROUP_ROUTE','Expedición');
define('TRAVEL_GROUP_CREATE','Crear grupo');
define('TRAVEL_GROUP_NO_MEMBERS','Por favor, nombra a los miembros de tu grupo');
define('TRAVEL_GROUP_MEMBERS','Participantes');
define('TRAVEL_GROUP_UPDATE','Actualizar grupo');
define('TRAVEL_GROUP_LEAVE','Dejar grupo');
define('TRAVEL_GROUP_CLOSE','Cerrar grupo');
define('TRAVEL_YOUR_LOCATION','Localización actual');
define('TRAVEL_ROUTE_PROGRESS','Esta es una zona #%n de tu ruta (has hecho %p%).');
define('TRAVEL_ROUTE_AWAY','Dejas la ruta pre-definida.');
define('TRAVEL_ROUTE_NEXT','La próxima zona es a <span style="font-weight:bold;color:#090;">%s</span>.');
define('TRAVEL_ROUTE_MAX_ZOMBIES','Durante la ruta te encontrarás con <span style="font-weight:bold;color:#f00;">%d zombies</span>.');
define('TRAVEL_ROUTE_ITEMS','Estos objetos están en tu ruta');
define('TRAVEL_ALL_GROUPS','Todos los grupos que viajan hoy');
define('TRAVEL_CHAOS','Caos. Nadie está aquí. ¿Quizá tú también deberías irte?');

# radar
define('RADAR_ERROR','Ocurrió un error. Datos no guardados.');
define('RADAR_BANNED','Los datos no parecen fiables y no han sido guardados.');
define('RADAR_SCOUT','El número de zombies ha sido guardado. ¡Bien hecho, explorador!');
define('RADAR_SCAVENGER','Estados de regeneración guardados. ¡Vivan los excavadores!');
define('RADAR_GUARDIAN','No toques la máquina, protege algo.');
define('RADAR_CITIZEN','Deja el sistema de radar. ¡Sólo Héroes!');
define('RADAR_HUNTER','Tienes un libro de supervivencia, no un manual, ¿verdad?');
define('RADAR_TAMER','¿Se hizo pis tu perro en los botones? Eeeew.');

# stats
define('STAT_ZOMBIE_TITLE','Ataques Zombies');
define('STATS_DEFOE','Temporada %d');
define('STATS_HARD','Temporada %d Pandemonio');
define('STAT_SOULS_TITLE','Puntos de alma');
define('STAT_REWARDS_TITLE','Distinciones');
define('STAT_TITLES_TITLE','Títulos');
define('STAT_CC_TITLE','Comparar ciudadanos');
define('STAT_ACTIVETOWNS_TITLE','Pueblos activos');
define('STAT_OLDTOWNS_TITLE','Pueblos viejos');
define('STAT_SCOUTS_TITLE','Exploradores');
define('STAT_ZOMBIE_INFO','');
define('STAT_ZOMBIE_BASE','Ataques Zombies - %d datos enviados desde %s pueblos');
define('DEATH_CALC','Calculadora de muertes <em>por haase</em>');
define('DEATH_CALC_ZOMBIES','zombies entrarán');
define('DEATH_CALC_CITIZENS','ciudadanos en el pueblo');
define('DEATH_CALC_PERSDEF','defensa personal');
define('DEATH_CALCULATE','¿Qué posibilidades tengo?');
define('COMPARE','Comparar');
define('MIN','Mínimo');
define('MAX','Máximo');
define('AVG','Media');
define('MED','Mediana');
define('COUNT_DATASETS','Nº de datos enviados');
define('YOUR_CITY','Tu pueblo');
define('GOOD_LUCK','¡Buena suerte!');
define('STAT_ACTIVETOWNS_INFO','');
define('STAT_OLDTOWNS_INFO','');
define('STAT_CITY_NAME','Nombre del pueblo');
define('STAT_LAST_DAY','Días sobrevividos');
define('STAT_CHAOS','Caos');
define('STAT_DEVAST','Devastado');
define('STAT_CHAOS_X','¡Caos!');
define('STAT_DEVAST_X','¡Portal destruido!');
define('STAT_SURVIVORS','Supervivientes');
define('STAT_WATER_WELL','Agua en el pozo');
define('STAT_WATER_BANK','Agua en el almacén');
define('STAT_JERRY_BANK','Bidones en el almacén');
define('STAT_DEF_ITEMS','Número de objetos defensivos');
define('STAT_LAST_ZOMBIES','Número de zombies anoche');
define('STAT_LAST_DEF','Defensa del pueblo anoche');
define('STAT_LAST_UPDATE','Última actualización');
define('ZOMBIE_SPREAD','Ataque zombie - día %d | temporada %s');
define('OBTAINABLE','Puede obtenerse por');
define('OGAME','Esta calculadora es para Zombinoia, no OGame. Sólo 40 ciudadanos pueden estar en un pueblo.');
define('YOU_WILL_SURVIVE','Sobrevivirás a este ataque con<br/>una posibilidad de');
define('SHOW_ONLY_OWN_TOWNS','Sólo mostrar mis pueblos');
define('SHOW_ONLY_TOWNS_WITH','Sólo mostrar pueblos con al menos');
define('SHOW_DEFOE_TOWNS','Mostrar pueblos normales');
define('SHOW_HARD_TOWNS','Mostrar pueblos Pandemonio');
define('SHOW_INTERPOLATED_TOWNS','Cambiar a pueblos que han sido o no han sido actualizados hoy');
define('STAT_MAP_SIZE','Tamaño del mapa');
define('SURVIVORS','Supervivientes');
define('BUILDINGS','Construcciones');
define('DEFENSIVE_OBJECTS','Objetos defensivos');
define('TOWN_DEFENSE','Defensa del pueblo');
define('TOWN_DEF_BASE','Defensa base del pueblo');
define('TOWN_DEF_BUILDINGS','Defensa del pueblo por construcciones');
define('TOWN_DEF_HOMES','Defensa del pueblo por casas de ciudadanos');
define('TOWN_DEF_GUARDS','Defensa del pueblo por Guardianes');
define('TOWN_DEF_ITEMS','Defensa del pueblo por objetos defensivos');
define('TOWN_DEF_UPGRADES','Defensa del pueblo por mejoras');
define('MAP','Mapa');
define('ATTACKS','Ataques');
define('CADAVER','Cadáver');
define('LAST_ATTACK','Ataquer de ayer');
define('NEXT_ATTACK','Ataque de hoy');
define('REWARDS','Recompensas');
define('TITLES','Títulos');
define('SOUL_POINTS', 'Puntos de alma');
define('POINTS', 'Puntos');
define('PROVIANT', 'Agua y comida');
define('GAMES', 'Historia del pueblo');
define('NO_DATA_AVAILABLE', 'Sin datos disponibles.');
define('RANKINGPOINTS', 'Puntos de clasificación actuales: %r supervivientes y %d muertos. ¡Estas cifras pueden ser inexactas!');

# toolbox
define('ADD','Añadir');
define('SAVE','Guardar');
define('EXPLORATION_LEVEL','Nivel de exploración');

# events
define('TOWN','Pueblo');
define('PRIMARY_CHOICE','Primera opción');
define('SECONDARY_CHOICE','Segunda opción ');
define('BACKUP_CHOICE','Última opción');
define('FTW','¡Hurra!');
define('TOWN_FULL','¡El pueblo está completo!');
define('REGISTRATION_TIMER','Abriremos las inscripciones en <span class="timeleft">%d</span> segundos.');
define('STATUS','Estado');
define('NONE_YET','Nadie aún.');
define('PRIMARY_BAILOUT','Estaré de reserva, por si acaso');
define('SECONDARY_BAILOUT','También estaré de reserva, por si acaso');
define('BACKUP_BAILOUT','En el peor de los casos, estaré de reserva aquí.');
define('NAME_HIDDEN','Nombre oculto');
define('Town points','Puntos del pueblo');
define('CITIZENS','Habitantes');
define('Citizens','Habitantes');
define('Zombie attack','Ataque de zombies');
define('Town defense','Defensa del pueblo');
define('Defensive items','Objetos de defensa');
define('Food supplies','Comida');
define('Water in bank',' Reservas de agua en el almacén');
define('Jerry cans','Bidones');
define('Coffee','Café');
define('Drugs','Drogas');
define('Alcohol','Alcohol');
define('Water in well','Reservas de agua en el pozo');
define('Explored map','Mapa explorado');
define('Explored zones','Zonas exploradas');
define('Depleted zones','Zonas agotadas');
define('Depletion ratio','% de agotamiento');
define('CHAOS_MODE','¡MODO CAOS!');
define('TOWN_DEVASTATED','¡El pueblo está devastado!');
define('GATES_OPEN','¡Portal abierto!');
define('GATES_CLOSED','Portal cerrado');
define('TOWN_SPY','¡Espía este pueblo!');
define('ESTIMATED_POINTS','Puntos estimados');
define('LAST_UPDATE','Última actualización');
define('DEAD_MEAT','Cadáveres');
define('DEFENSE','Defensa');
define('SUPPLIES','Provisiones');
define('STATISTICS','Estadísticas');
define('TOWN_DEAD','¡Este pueblo está muerto!');
define('TOWN_DEAD_MAYBE','Este pueblo podría estar muerto.');