<?php
// language specific strings for use in Oval Office

// syntax: define('VAR', 'value');
/*
define('','');
define('','');
define('','');
define('','');
define('','');
define('','');
*/

# global
define('ERROR_CODE', 'Fehlercode');
define('ERROR_XML_DEFAULT', 'Fehler in der XML-Verarbeitung.');
define('CATEGORY','Kategorie');
define('ITEM','Gegenstand');
define('DAY','Tag');
define('STATUS_QUO','Stand');
define('TIME_APPENDIX',' Uhr');
define('CAUTION', 'Achtung');
define('AMP','&');
define('NOTE','Hinweis');
define('PRESET_SAVE', 'Als Vorlage speichern');
define('PRESET_LOAD', 'Vorlage laden');
define('PRESET_SAVED', 'Vorlage gespeichert.');
define('PRESET_LOADED', 'Vorlage geladen.');
define('ERROR_OCCURED', 'Ein Fehler ist aufgetreten.');
define('COUNT', 'Anzahl');
define('ENTER_VALUES', 'Eintragen');
define('NAME', 'Name');
define('LOCATION', 'Aufenthaltsort');
define('DEATHCAUSE', 'Todesursache');
// jobs
define('CITIZEN', 'Bürger');
define('CITIZEN_NOJOB', 'Arbeitssuchend');
define('SCAVENGER', 'Buddler');
define('SCOUT', 'Aufklärer');
define('TAMER', 'Dresseur');
define('GUARDIAN', 'Wächter');
define('DEAD_CITIZEN', 'Verstorben');
define('AP', 'AP');
define('CP', 'KP');
define('KM', 'km');
// city and directions
define('CITY', 'Stadt');
define('Nx','Norden');
define('Wx','Westen');
define('Sx','Süden');
define('Ex','Osten');
define('NEx','Nordosten');
define('NWx','Nordwesten');
define('SEx','Südosten');
define('SWx','Südwesten');
define('N','N');
define('W','W');
define('S','S');
define('E','O');
define('NE','NO');
define('NW','NW');
define('SE','SO');
define('SW','SW');
define('ZOMBIE', 'Zombie');
define('ZOMBIES', 'Zombies');
define('ZOMBIEX','%s');
define('EXISTENT','vorhanden');
define('TODAY','heute');
define('YESTERDAY','gestern');
define('APPROXY','ca.');

# bank
define('Rsc', 'Baumaterialien');
define('Food', 'Lebensmittel');
define('Armor', 'Verteidigung');
define('Drug', 'Apothekenpflichtiges');
define('Weapon', 'Waffenarsenal');
define('Misc', 'Sonstiges');
define('Furniture', 'Deko & Ausbau');
define('Box', 'Taschen & Wagen');
define('GRAPH_SETTINGS', 'Einstellungen für Grafiken');
define('GRAPH_TYPE', 'Diagrammtyp');
define('GRAPH_BARS', 'Balken');
define('GRAPH_LINES', 'Linien');
define('GRAPH_MAX_VALUES','Maximal-Anzahl Kohorten');
define('BANK_CONTENT', 'Bankinhalt');
define('BANK_CHANGE_MSG', 'Zahlen in Klammern spiegeln die Veränderung gegenüber dem Vortag wider.');
define('BROKEN', 'kaputt');
define('BANK_HISTORY_MSG', 'In einem alten verstaubten Buch auf einer Art Altar entdeckst Du Zeichnungen von Objekten, die Du nur noch vage in Erinnerung hast.');
define('GRAPH_BANK_TITLE','Entwicklung der Inventarzahlen');

# bauamt
define('CONSTRUCTION_YARD_TITLE','Das Bauamt');
define('SELECT_NONE','Auswahl löschen');
define('SELECT_ALL','Alles auswählen');
define('GET_CONSTRUCTION_PERMIT','Bauantrag stellen');
define('ALREADY_BUILT','Bereits gebaut!');
define('TEMPORARY_BUILDING','Temporäres Gebäude');
define('REMAINS','verbleibt');
define('REMAIN','verbleiben');
define('ITEMS_REMAINING', 'Es %s %d.');
define('MISSES','fehlt');
define('MISS','fehlen');
define('ITEMS_MISSING', 'Es %s noch %d!');
define('CONSTRUCTION_PERMIT_REQUESTED', 'Bauantrag gestellt für %d Gebäude');
define('VP_GAIN', 'Der Bau wird insgesamt %s VP bringen.');
define('WILLS','wird');
define('WILL','werden');
define('VP_ITEM','Verteidigungsgegenstand');
define('VP_ITEMS','Verteidigungsgegenstände');
define('VP_USE','Allerdings %s %d %t verbraucht.');
define('REQUIRED_RESOURCES','Benötigte Baustoffe');
define('REQUIRED_AP_BUILD','Benötigte AP für den Bau');
define('REQUIRED_AP_WORKSHOP','Benötigte AP in der Werkstatt');
define('CONSTRUCTION_PERMIT','BAUGENEHMIGUNG');
define('REQUESTED_BY','ausgefertigt im Oval Office auf Antrag von %s');
define('CONSTRUCTIONS_PERMITTED','Genehmigt %s [g]%d Gebäude[/g]');
define('HAS_BEEN','wurde');
define('HAVE_BEEN','wurden');
define('WORKSHOP_CONVERSIONS', 'In der Werkstatt könnten erzeugt werden');
define('REQUIRED_STEPS', '%d Schritte notwendig.');
define('FACTORY','Manufaktur');
define('SAW','Säge');
define('EXIST','vorhanden');
define('PERMIT_COPY_NOTICE', 'Mit <span style="font-variant:small-caps;">Strg/Ctrl+C</span> kannst Du die Baugenehmigung in die Zwischenablage kopieren und von dort aus per <span style="font-variant:small-caps;">Strg/Ctrl+V</span> im Stadtforum einfügen.');

# ema
define('EMA_NONAME', 'Ihr Name konnte nicht korrekt entziffert werden. Die Nutzung des Planers ist daher nur unzureichend möglich und kann Fehler aufweisen.');
define('EMA_OFFICE', 'Meldestelle');
define('EMA_REGISTER','Registerauskunft');
define('EMA_OFFICE_TITLE','Computergestützte Selbstauskunft');
define('EMA_OFFICE_INFO','Für eine genaue Planung und zum Schutz aller Bürger ist die Verfügbarkeit eines jeden sehr wichtig. Bitte geben Sie hier Ihre An- bzw. Abwesenheit für die nächsten Tage an. Die Eintragung erfolgt stundengenau.');
define('EMA_FORM_DAY','Angaben für Tag');
define('EMA_S_THIRSTY','durstig');
define('EMA_S_HANGOVER','verkatert');
define('EMA_S_TERRORIZED','Angststarre');
define('EMA_S_CLEAN','clean');
define('EMA_S_TOPFORM','Top im Form');
define('EMA_S_SAFE','Panzerschrank');
define('EMA_CARE','Lunchpaket besteht aus');
define('EMA_S_WATER','Wasser (6 AP)');
define('EMA_S_FOOD_DEFOE','Normales Essen (6 AP)');
define('EMA_S_FOOD_YUMMY','Leckeres Essen (7 AP)');
define('EMA_S_STEROID','Steroide (6 AP)');
define('EMA_S_TWINOID','Twinoid (8 AP)');
define('EMA_S_ALCOHOL','Alkohol (6 AP)');
define('EMA_S_COFFEE','Kaffee (4 AP)');
define('EMA_S_ALARM','Wecker (1 AP)');
define('EMA_S_GAMBLE','Glücksspiel (1 AP)');
define('EMA_S_SIESTA','Ruheecke (2 AP)');
define('EMA_S_2NDLUNG','Zweite Lunge (6 AP)');
define('EMA_LIST','Übersichtsliste');
define('EMA_REGISTER_INFO','Die fleißigen Mitarbeiterinnen protokollieren die Zustände und Aufenthaltsorte der Bürger. Eine von ihnen hängt gerade eine aktualisierte Liste an die Eingangstür.');
define('DC1','Dehydriert');
define('DC2','Selbstmord durch Erhängen');
define('DC3','Selbstmord durch Zyanid');
define('DC4','Volksjustiz (Tod durch Erhängen)');
define('DC5','In der Außenwelt verschwunden');
define('DC6','Beim gestrigen Angriff aufgefressen');
define('DC7','Tod durch Entzug');
define('DC8','Tod durch Infektion');
define('DC9','Kopfschuss (Account von Admin gelöscht)');
define('DC10','Seele aufgelöst (Account gelöscht)');
define('DC11','Vergiftet');
define('DC12','Vom Ghul gefressen');
define('DC13','Aggression (Ghul)');
define('DC14','Verhungerter Ghul');
define('DC0','Todesursache unbekannt');
define('EMA_T_NONE','keine Angabe');
define('EMA_T_NOT','nicht online');
define('EMA_T_SPORA','sporadisch online');
define('EMA_T_ACTIV','aktiv online');
define('EMA_B_WATER','AP durch Wasser');
define('EMA_B_FOOD','AP durch Essen');
define('EMA_B_STEROID','AP durch Steroide');
define('EMA_B_TWINOID','AP durch Twinoid');
define('EMA_B_ALCOHOL','AP durch Alkohol');
define('EMA_B_COFFEE','AP durch Kaffee');
define('EMA_B_ALARM','AP durch Kreischenden Wecker');
define('EMA_B_GAMBLE','AP durch Glücksspiel');
define('EMA_B_SIESTA','AP durch Ruheecke');
define('EMA_B_2NDLUNG','AP durch Zweite Lunge');
define('EMA_TOGGLE_CODES', 'Verfügbarkeitssymbole ein- bzw. ausblenden');

# map
define('ZONE_D_0','Sichere Zone');
define('ZONE_D_1','Einzelner Zombie');
define('ZONE_D_2','Zombiemeute');
define('ZONE_D_3','Zombiehorde');
define('ZONE_D_4','Ganz viele Zombies');
define('ZONE_DIG','Es müssen noch <strong>%d</strong> Haufen entfernt werden.');
define('COORDS','Koordinaten');
define('ZONE_DRIED','Diese Zone ist <strong>leer</strong>.');
define('ZONE_DANGER','Gefahrenstufe');
define('ZONE_NYV','Noch nie besucht');
define('ZONE_NVT','Heute noch nicht besucht');
define('ZONE_LASTUPDATE','Zuletzt aktualisiert am');
define('ZONE_LASTVISIT','Letzter Besuch');
define('ZONE_LASTRADAR','Letzte Radarmeldung');
define('ZONE_ITEMSONGROUND','Gegenstände auf dem Boden');
define('MAP_OP_TITLE','Zonendetails');
define('MAP_OP_INFO','Zoneninfo');
define('MAP_OP_SETTINGS','Kartenoptionen');
define('MAP_OP_EXPEDITIONS','Expeditionen');
define('MAP_LAYER_ZCORI','Zombies (Originale DV-Farben)');
define('MAP_LAYER_ZCDET','Zombies (Detailfarben)');
define('MAP_LAYER_CITCOUNT','Bürgerzahlen (Farben)');
define('MAP_LAYER_ZOMCOUNT','Zombiezahlen');
define('MAP_LAYER_ZONEMARKER','Zonenmarker');
define('MAP_LAYER_DIRCOLOR','Himmelsrichtungen (Farben)');
define('MAP_LAYER_DIRBORDER','Himmelsrichtungen (Grenzen)');
define('MAP_LAYER_WATCHTOWER','Wachturmbonus (Farben)');
define('MAP_LAYER_SEARCH','Suchergebnisse');
define('MAP_SEARCH_CAT','Kategorie wählen oder');
define('MAP_SEARCH_ITEM','Item eingeben');
define('MAP_SEARCH_FIND','Finden!');
define('MAP_LEGEND','Legende');
define('MAP_ALL_EXPEDITIONS','Alle Expeditionen');
define('MAP_SEARCH_TOGGLE_VIEW','Ansicht wechseln');
define('MAP_SEARCH_TOGGLE_INFO','Zwischen normaler Ansicht und Code für das Stadtforum wechseln');
define('MAP_SEARCH_ITEM_FOUND','%s gefunden auf');
define('ZONE_INFO_ASOF','Info von');
define('MAP_SEARCH_ITEM_NOT_FOUND','Leider konnte keine Zone mit %s gefunden werden.');
define('MAP_SEARCH_AJAXCOMPLETE','Meinst Du ...');
define('MAP_SEARCH_RUNNING','Suche nach %s läuft ...');
define('MAP_SEARCH_NOTHING_FOUND','Nix passendes gefunden.');
define('MAP_SEARCH_SHORT_TERM','Bitte mindestens drei Buchstaben eingeben.');
define('ZONE_REGENERATED','Zone ist regeneriert.');
define('ZONE_NEW_REGENERATED','Zone ist unberührt (und voll).');
define('ZONE_NOT_REGENERATED','Zone ist <em>nicht</em> regeneriert.');
define('ZONE_RADAR_INFO','Zoneninfo laut Radar');

# travel
define('Ngo','NORDEN (oben)');
define('Wgo','WESTEN (links)');
define('Sgo','SÜDEN (unten)');
define('Ego','OSTEN (rechts)');
define('TRAVEL_TITLE','Reisebüro');
define('TRAVEL_INFO','Für gelangweilte Stadtbewohner bieten wir ungeführte Ausflüge in die Wüste an. In Ermangelung geeigneter Fahrzeuge sind derzeit nur Exkursionen per pedes im Angebot.');
define('TRAVEL_YOUR_GROUP','Deine Reisegruppe');
define('TRAVEL_NO_GROUP','Du gehörst noch keiner Reisegruppe an. Gründe eine neue Gruppe oder lass Dich von einer anderen Gruppe hinzufügen.');
define('TRAVEL_GROUP_NAME','Gruppenname');
define('TRAVEL_NEW_GROUP_NAME','s Reisegruppe');
define('TRAVEL_GROUP_PERSISTENT','Gruppe dauerhaft speichern');
define('TRAVEL_GROUP_ROUTE','Laufroute');
define('TRAVEL_GROUP_CREATE','Reisegruppe gründen');
define('TRAVEL_GROUP_NO_MEMBERS','Du hast die Teilnehmer Deiner Reisegruppe noch nicht definiert.');
define('TRAVEL_GROUP_MEMBERS','Teilnehmer');
define('TRAVEL_GROUP_UPDATE','Reisegruppe aktualisieren');
define('TRAVEL_GROUP_LEAVE','Reisegruppe verlassen');
define('TRAVEL_GROUP_CLOSE','Reisegruppe auflösen');
define('TRAVEL_YOUR_LOCATION','Aktueller Standort');
define('TRAVEL_ROUTE_PROGRESS','Das ist Punkt Nummer %n auf der Route (%p% geschafft).');
define('TRAVEL_ROUTE_AWAY','Du bist von der Route abgewichen.');
define('TRAVEL_ROUTE_NEXT','Die nächste Zone liegt im <span style="font-weight:bold;color:#090;">%s</span>.');
define('TRAVEL_ROUTE_MAX_ZOMBIES','Auf der Route muss nach bestätigten Meldungen mit bis zu <span style="font-weight:bold;color:#f00;">%d Zombies</span> gerechnet werden.');
define('TRAVEL_ROUTE_ITEMS','Unterwegs liegen diese Objekte herum');
define('TRAVEL_ALL_GROUPS','Alle für heute angemeldeten Reisegruppen');
define('TRAVEL_CHAOS','Die Mitarbeiterinnen des Reisebüros sind in Panik geflohen. Die Büroräume sehen verwüstet aus. Ein Windhauch pustet eines der gelben Klebezettelchen von einem Monitor in Deine Richtung. Mit zittriger Hand wurde darauf eine kurze Notiz gekritzelt:<br/><br/><em>"Marie, ich liebe Dich! Aber ich hau jetzt ab..."</em><br/><br/>Während Du Dich noch fragst, wer Marie wohl war, hörst Du draußen Raben krächzen. Vielleicht solltest Du Dich auch auf den Weg machen.');

# radar
define('RADAR_ERROR','Es ist ein Fehler aufgetreten, die Radardaten konnten nicht gespeichert werden.');
define('RADAR_BANNED','Die Informationen sind unglaubwürdig. Die Daten wurden nicht übertragen.');
define('RADAR_SCOUT','Die Zombieschätzungen wurden ins Oval Office übertragen. Gutes Auge, Aufklärer!');
define('RADAR_SCAVENGER','Der Regenerationsstatus der angrenzenden Felder wurde übertragen. Buddler FTW!');
define('RADAR_GUARDIAN','Spiel nicht an der Maschine herum, Wächter. Du sollst aufpassen!');
define('RADAR_CITIZEN','Überlass die Radarfunktion den Helden, Bürger! Willst Du nicht weiter graben?');
define('RADAR_TAMER','Hat Dein Hund schon wieder auf das Funkgerät gepinkelt? Geh Gassi!');

# stats
define('STAT_ZOMBIE_TITLE','Zombieangriffe');
define('STAT_REWARDS_TITLE','Auszeichnungen');
define('STAT_TITLES_TITLE','Titel');
define('STAT_ACTIVETOWNS_TITLE','Aktive Städte');
define('STAT_OLDTOWNS_TITLE','Alte Städte');
define('STAT_ZOMBIE_INFO','Ein Schild am Eingang weist den Besucher darauf hin, dass die Raumgestaltung wegen des versehentlichen Explodierens einer Schießpulverbombe bitte nicht beachtet werden soll. Die Aufräumarbeiten sind im Gange. Dennoch soll der Service genutzt werden können. Leider sieht man außer einem alten Ausdruck nicht viel.</p><p>Als Du näher an die Pinwand herantritts, siehst Du, dass der Ausdruck kompliziert gefaltet ist. Wenn Du einen Zeileneintrag berührst, klappt eine Grafik heraus.');
define('STAT_ZOMBIE_BASE','Daten zu Zombieangriffen - %d Datensätze aus %s Städten');
define('DEATH_CALC','Todesrechner <em>von haase</em>');
define('DEATH_CALC_ZOMBIES','Zombies dringen ein');
define('DEATH_CALC_CITIZENS','Bürger in der Stadt');
define('DEATH_CALC_PERSDEF','persönliche Verteidigung');
define('DEATH_CALCULATE','Wie stehen meine Chancen?');
define('MIN','Minimum');
define('MAX','Maximum');
define('AVG','Mittelwert');
define('MED','Median');
define('COUNT_DATASETS','Anzahl Datensätze');
define('YOUR_CITY','Deine Stadt');
define('GOOD_LUCK','Viel Glück!');
define('STAT_ACTIVETOWNS_INFO','Sowohl die Liste der aktiven als auch die der alten Städte berücksichtigt nur Daten ab dem Start der dritten Saison (21.02.2011). Die ausgegrauten Zeilen zeigen an, dass diese Daten von gestern stammen und die Stadt dementsprechend schon tot sein könnte.');
define('STAT_OLDTOWNS_INFO','Zu den <em>Alten Städten</em> gehören Städte, von denen sich weder gestern noch heute nicht wenigstens ein Spieler hier eingeloggt hat.');
define('STAT_CITY_NAME','Name der Stadt');
define('STAT_LAST_DAY','Überlebte Tage');
define('STAT_CHAOS','Chaos');
define('STAT_DEVAST','Verwüstet');
define('STAT_CHAOS_X','Es herrscht Chaos!');
define('STAT_DEVAST_X','Die Stadt wurde zerstört!');
define('STAT_SURVIVORS','Überlebende');
define('STAT_WATER_WELL','Brunnenwasser');
define('STAT_WATER_BANK','Wasser in der Bank');
define('STAT_JERRY_BANK','Kanister in der Bank');
define('STAT_DEF_ITEMS','Anzahl Verteidigungsgegenstände');
define('STAT_LAST_ZOMBIES','Anzahl Zombies beim letzten Angriff');
define('STAT_LAST_DEF','Stadtverteidigung beim letzten Angriff');
define('STAT_LAST_UPDATE','Letzte Aktualisierung');


