<?php
// language specific strings for use in Oval Office

// syntax: define('VAR', 'value');
/*
define('','');
define('','');
define('','');
define('','');
define('','');
define('','');
*/

define('GAME_ICON_SERVER','http://data.die2nite.com/gfx/icons/item_');
define('GAMESERVER_ITEM','http://data.die2nite.com/gfx/icons/item_');
define('GAMESERVER_TAG','http://data.die2nite.com/gfx/icons/tag_');
define('GAMESERVER_ICON','http://data.die2nite.com/gfx/icons/');
define('GAMESERVER_SMILEY','http://www.die2nite.com/gfx/forum/smiley/');

define('DATETIME_FULL', '%e. %B %Y | %H:%M');
define('DATETIME_MINI', '%e.%m.%Y, %H:%M');

# global
define('VERSION','version');
define('MAINTENANCE_MSG','There are some zombies breaking the interiour, please wait until we fixed it again.');
define('ERROR_CODE', 'error code');
define('ERROR_XML_DEFAULT', 'xml error');
define('CATEGORY','category');
define('ITEM','item');
define('DAY','day');
define('DAYS','days');
define('DAYS_DATIV','days');
define('STATUS_QUO','status quo');
define('TIME_APPENDIX','');
define('CAUTION', 'Caution');
define('AMP','&');
define('NOTE','Note');
define('PRESET_SAVE', 'Save preset');
define('PRESET_LOAD', 'Load preset');
define('PRESET_SAVED', 'Preset saved.');
define('PRESET_LOADED', 'Preset loaded.');
define('ERROR_OCCURED', 'An error occured.');
define('COUNT', 'number');
define('AMOUNT', 'amount');
define('ENTER_VALUES', 'Submit');
define('NAME', 'Name');
define('LOCATION', 'Location');
define('DEATHCAUSE', 'Cause of death');
define('SEASON','Season');
// jobs
define('RESIDENT', 'resident');
define('CITIZEN', 'citizen');
define('CITIZEN_NOJOB', 'unemployed');
define('HERO','Hero');
define('HEROS','Heroes');
define('SCAVENGER', 'Scavenger');
define('SCOUT', 'Scout');
define('TAMER', 'Tamer');
define('GUARDIAN', 'Guardian');
define('HUNTER', 'Survivalist');
define('TECH', 'Technician');
define('SHAMAN', 'Shaman');
define('DEAD_CITIZEN', 'dead');
define('DEADS','dead');
define('BANNED','banned');
define('AP', 'AP');
define('CP', 'CP');
define('KM', 'km');
// city and directions
define('CITY', 'City');
define('Nx','North');
define('Wx','West');
define('Sx','South');
define('Ex','East');
define('NEx','North-east');
define('NWx','Nord-west');
define('SEx','South-east');
define('SWx','South-west');
define('N','N');
define('W','W');
define('S','S');
define('E','E');
define('NE','NE');
define('NW','NW');
define('SE','SE');
define('SW','SW');
define('ZOMBIE', 'zombie');
define('ZOMBIES', 'zombies');
define('ZOMBIEX','%s');
define('EXISTENT','available');
define('TODAY','today');
define('YESTERDAY','yesterday');
define('APPROXY','appr.');
define('DEFOE_TOWN','Normal towns');
define('HARD_TOWN','Pandemonium');
define('ATTACK_TODAY','Today\'s attack estimations');
define('ATTACK_TOMORROW','Tomorrow\'s attack estimations');
define('CITIZENS_OUTSIDE','citizens outside');

define('FOYER_INTRO','Introduction');
define('FOYER_ID','Identification');
define('FOYER_GM','Addons & Scripts');

# mail
define('YOUR_MAILBOX', 'Oval Post-Office');
define('YOUR_MESSAGES', 'Your messages');
define('YOUR_FRIENDS', 'Your contacts');
define('INVITE', 'Invite');
define('USER_NOT_YET_LOGGED_IN', 'This user has not activated his p.o. box, yet.');
define('USER_UNKNOWN', 'Unknown user name');
define('USER_IGNORES_YOU', 'This user does not want ot be contacted by you.');
define('USER_INVITED_YOU', 'This user did send an invitation to you. Please answer that request.');
define('USER_ALREADY_INVITED', 'You already invited this user, wait for the reply.');
define('USER_INVITED','You invited %s to be one of your contacts.');
define('USER_NOT_YOUR_FRIEND','This user is not in your contact list, yet.');
define('PENDING','Pending');
define('INVITES', 'Invitations');
define('ACTIVE_CONTACTS','Friends');
define('ACCEPT_REQUEST','Accept invitation');
define('DECLINE_REQUEST','Decline invitation');
define('IGNORE_REQUEST','Ignore user');
define('SEND_MSG', 'Send message');
define('MSG_SENT', 'Message sent.');
define('USER_ACCEPTED', '%s is now on of you contacts.');
define('FROM','From');
define('TO','To');
define('SUBJECT','Subject');
define('TIME_SENT','Sent');
define('TIME_RECEIVED', 'Received');
define('TRASH', 'Del');
define('TRASH_MAIL', 'Delete mail');
define('NO_MSGS','No messages');
define('ANSWER_MSG','Reply');
define('SELFINVITE','No real friends, eh? That\'s sad.');
define('USER_DECLINED', 'You declined %s\'s invitation.');
define('USER_WITHDRAWN', 'You withdrew the invitation to %s.');
define('USER_DELETED', '%s is no longer one of your contacts.');
define('DELETE_CONTACT', 'Delete contact');
define('WITHDRAW_INVITE', 'Withdraw invite');

# bank
define('Rsc', 'Resources');
define('Food', 'Food');
define('Armor', 'Defences');
define('Drug', 'Drugs');
define('Weapon', 'Weapons');
define('Misc', 'Misc');
define('Furniture', 'Furniture');
define('Box', 'Containers & boxes');
define('GRAPH_SETTINGS', 'Graph settings');
define('GRAPH_TYPE', 'Type of diagram');
define('GRAPH_BARS', 'bars');
define('GRAPH_LINES', 'lines');
define('GRAPH_MAX_VALUES','Maximum # of groups');
define('BANK_CONTENT', 'Bank');
define('BANK_CHANGE_MSG', 'Numbers in parenthesis show difference compared to previous day.');
define('BROKEN', 'broken');
define('BANK_HISTORY_MSG', 'An old book contains drawings of long forgotten items.');
define('GRAPH_BANK_TITLE','Change over time');
define('WWATER','Water (bank)');
define('WWELL','Water (well)');
define('FOOD','Food');
define('DRUGS','Drugs');
define('ALCOHOL','Alcohol');
define('COFFEE','Coffee');

# bauamt
define('CONSTRUCTION_YARD_TITLE','Building authority');
define('SELECT_NONE','Select none');
define('SELECT_ALL','Select all');
define('SHOW_BPONLY','Show available ones only');
define('SHOW_ALL','Show all');
define('GET_CONSTRUCTION_PERMIT','Apply!');
define('ALREADY_BUILT','Already built!');
define('TEMPORARY_BUILDING','Temporary building');
define('TEMPORARY','temporary');
define('MARK_AS_BLUEPRINT_FOUND','Mark this bluebrint as now available.');
define('MARK_AS_BLUEPRINT_LOST','Mark this bluebrint as not available.');
define('REMAINS','remains');
define('REMAIN','remain');
define('ITEMS_REMAINING', '%d %s.');
define('MISSES','is missing');
define('MISS','are missing');
define('ITEMS_MISSING', '%d %s!');
define('CONSTRUCTION_PERMIT_REQUESTED', 'Application for %d buildings');
define('VP_GAIN', 'The city will gain %s defence.');
define('WILLS','will be');
define('WILL','will be');
define('VP_ITEM','defensive object');
define('VP_ITEMS','defensive objects');
define('VP_USE','However, %d %t %s used.');
define('REQUIRED_RESOURCES','Required resources');
define('REQUIRED_AP_BUILD','Required AP for building');
define('REQUIRED_AP_WORKSHOP','Required AP for converting');
define('CONSTRUCTION_PERMIT','CONSTRUCTION PERMIT');
define('REQUESTED_BY','issued by Oval Office on application by %s');
define('CONSTRUCTIONS_PERMITTED','Approved %s [g]%d building(s)[/g]');
define('HAS_BEEN','is');
define('HAVE_BEEN','are');
define('WORKSHOP_CONVERSIONS', 'Available conversions');
define('REQUIRED_STEPS', '%d steps required.');
define('FACTORY','Factory');
define('SAW','Hacksaw');
define('EXIST','available');
define('PERMIT_COPY_NOTICE', 'By pressing <span style="font-variant:small-caps;">Ctrl+C</span> you may copy this permit and paste it to forums by using <span style="font-variant:small-caps;">Ctrl+V</span>.');

# ema
define('EMA_NONAME', 'You name could not be read.');
define('EMA_OFFICE', 'Citizen availability');
define('EMA_REGISTER','Citizen register');
define('EMA_OFFICE_TITLE','CADOPA - Computer assisted disclosure of personal attendance');
define('EMA_OFFICE_INFO','For detailled planning please provide your daily online status.');
define('EMA_OFFICE_TUTORIAL','<h4 style="cursor:pointer;" onclick="$(\'.ema-tut\').toggleClass(\'hideme\');"><span style="float:right;font-weight:normal;font-style:italic;">Click to toggle</span>Quick tutorial</h4><p class="ema-tut hideme">This registers purpose is to collect data about each residents availability and status for upcoming days. Especially for expeditions this may be helpful for the participants to agree on joint times for eating, drinking or taking drugs along the way. It could also help to assess someones capability to come online shortly before the attack and make a decision on whether the gates can be closed or not.</p><p class="ema-tut hideme">You can set your current status (or the one you will have tomorrow) which is most important to calculate the available CP (this information is used in travel agancy, too). Thirsty or hangover status for example could indicate that the respective citizen should take a shorter route or won\'t be able to drink alcohol.</p><p class="ema-tut hideme">Your lunch package sums up your available AP for the day which is essential for planning routes.</p><p class="ema-tut hideme">The colored boxes finally shall be used to provide information on your online status. Red would be something like "I am definitely not online.", yellow indicates times when you have online access but won\'t be logged into D2N all the time and green is for your active participation.</p><p class="ema-tut hideme">You can save a preset representing your most common settings so you don\'t have to reset the status and times for each day. The more citizens use this function the better the overview gets. Users with color view issues can switch to symbols by using the link below the submit button.</p>');
define('EMA_FORM_DAY','Attendance for day');
define('EMA_S_THIRSTY','thirsty');
define('EMA_S_HANGOVER','hangover');
define('EMA_S_TERRORIZED','terrorized');
define('EMA_S_CLEAN','clean');
define('EMA_S_TOPFORM','Hero: healthy body');
define('EMA_S_SAFE','Hero: glass armor');
define('EMA_CARE','Your lunch package');
define('EMA_S_WATER','Water (6 AP)');
define('EMA_S_FOOD_DEFOE','Standard food (6 AP)');
define('EMA_S_FOOD_YUMMY','Premium food (7 AP)');
define('EMA_S_STEROID','Steroids (6 AP)');
define('EMA_S_TWINOID','Twinoid 500mg (8 AP)');
define('EMA_S_ALCOHOL','Alcohol (6 AP)');
define('EMA_S_COFFEE','Coffee (4 AP)');
define('EMA_S_ALARM','Alarm clock (1 AP)');
define('EMA_S_GAMBLE','Gambling (1 AP)');
define('EMA_S_SIESTA','Siesta Time™ (2 AP)');
define('EMA_S_2NDLUNG','Hero: Second wind (6 AP)');
define('EMA_LIST','List of attendance');
define('EMA_REGISTER_INFO','');
define('DC1','Dehydrated');
define('DC2','Suicide (admin)');
define('DC3','Suicide by Cyanide');
define('DC4','Hung');
define('DC5','Died outside');
define('DC6','Killed by zombies in town');
define('DC7','Withdrawal');
define('DC8','Infection');
define('DC9','Head shot (account deleted by admin)');
define('DC10','Vaporized (account deleted)');
define('DC11','Poisoned');
define('DC12','Eaten by ghoul');
define('DC13','Aggression (ghoul)');
define('DC14','Starved ghoul');
define('DC15','Meat Locker');
define('DC0','unknown cause');
define('EMA_T_NONE','n/a');
define('EMA_T_NOT','not online');
define('EMA_T_SPORA','sporadically online');
define('EMA_T_ACTIV','actively online');
define('EMA_B_WATER','AP from water');
define('EMA_B_FOOD','AP from food');
define('EMA_B_STEROID','AP from steroids');
define('EMA_B_TWINOID','AP from Twinoid 500mg');
define('EMA_B_ALCOHOL','AP from alcohol');
define('EMA_B_COFFEE','AP from coffee');
define('EMA_B_ALARM','AP from alarm clock');
define('EMA_B_GAMBLE','AP from gambling');
define('EMA_B_SIESTA','AP from Siesta Time™');
define('EMA_B_2NDLUNG','AP from second wind');
define('EMA_TOGGLE_CODES', 'switch colors/symbols');
define('CADAVER_GARBAGED', 'Dragged out of town');
define('CADAVER_SPRINKLED', 'Sprinkled');
define('BY','by');
define('HOURS','hours');
define('LOC_INTOWN','inside town');
define('LOC_ATDOOR','at town gates');
define('EEO','e. &amp; e.o.');

# map
define('ZONE_D_0','Secured zone');
define('ZONE_D_1','Isolated zombie');
define('ZONE_D_2','Pack of zombies');
define('ZONE_D_3','Horde of zombies');
define('ZONE_D_4','Full of zombies');
define('ZONE_DIG','Building has to be cleared <strong>%d</strong> times.');
define('COORDS','coordinates');
define('ZONE_DRIED','This zone is <strong>depleted</strong>.');
define('BUILDING_DRIED','This building is <strong>depleted</strong>.');
define('BUILDING_REGENERATED','This building is <strong>depleted</strong>.');
define('ZONE_DANGER','danger level');
define('ZONE_NYV','Not yet visited');
define('ZONE_NVT','Not visited today');
define('ZONE_LASTUPDATE','Last update');
define('ZONE_LASTVISIT','Last visit');
define('ZONE_LASTRADAR','Last radar');
define('ZONE_ITEMSONGROUND','Items on ground');
define('MAP_OP_TITLE','Zone details');
define('MAP_OP_INFO','Zone info');
define('MAP_OP_STORM','Sturm');
define('MAP_OP_SETTINGS','Options');
define('MAP_OP_EXPEDITIONS','Expeditions');
define('MAP_LAYER_ZCORI','Zombies (D2N colors)');
define('MAP_LAYER_ZCDET','Zombies (detailled colors)');
define('MAP_LAYER_CITCOUNT','Citizen');
define('MAP_LAYER_ZOMCOUNT','Zombie figures');
define('MAP_LAYER_ZONEMARKER','Zone marker');
define('MAP_LAYER_DIRCOLOR','Directions (overlay)');
define('MAP_LAYER_DIRBORDER','Directions (borders)');
define('MAP_LAYER_WATCHTOWER','Watch tower jump radius');
define('MAP_LAYER_SEARCH','Search results');
define('MAP_SEARCH_CAT','Choose category or');
define('MAP_SEARCH_ITEM','enter item');
define('MAP_SEARCH_FIND','Find!');
define('MAP_LEGEND','Legend');
define('MAP_ALL_EXPEDITIONS','All expeditions');
define('MAP_SEARCH_TOGGLE_VIEW','Toggle display');
define('MAP_SEARCH_TOGGLE_INFO','Switch from default view to forums formatted version');
define('MAP_SEARCH_ITEM_FOUND','%s found at');
define('ZONE_INFO_ASOF','as of');
define('MAP_SEARCH_ITEM_NOT_FOUND','Sorry, no zone with %s found.');
define('MAP_SEARCH_AJAXCOMPLETE','Did you mean ...');
define('MAP_SEARCH_RUNNING','Search for %s is running ...');
define('MAP_SEARCH_NOTHING_FOUND','Nothing found.');
define('MAP_SEARCH_SHORT_TERM','Please enter at least three letters.');
define('ZONE_REGENERATED','Zone has replenished.');
define('ZONE_NEW_REGENERATED','Zone has not been visited yet (full).');
define('ZONE_NOT_REGENERATED','Zone has <em>not</em> regeneriert.');
define('ZONE_RADAR_INFO','Zone radar info');
define('WATCHTOWER','Watchtower');
define('VISION','Memory of a citizen');
define('MAP_COLOR_BACK','Zone background color');
define('NO_BACKCOLOR','No background color');
define('MAP_RADIUS','Radii');
define('MAP_INFOLAYER','Misc');
define('MAP_SEARCHFORM','Search on map');
define('MAP_LAYER_VISITSTATUS','Visiting status');
define('MAP_LAYER_CITIDOT','Citizen dots');
define('MAP_LAYER_HUMCOUNT','Citizen count');
define('MAP_LAYER_WATCHTOWER1','Watchtower bonus (level 4)');
define('MAP_LAYER_WATCHTOWER2','Watchtower bonus (level 5)');
define('MAP_LAYER_RADIUS6','6AP radius');
define('MAP_LAYER_RADIUS9','9AP radius');
define('MAP_LAYER_RADIUS15','15km radius');
define('MAP_LAYER_REGENSTATUS','Zone status (depricated?)');
define('MAP_LAYER_REGENERATION','Scavenger radar');
define('LAST_OFFICIAL_COUNT','Last official count');
define('EDIT_ZONE_INFO','Edit zone information');
define('REGISTER_STORM','Register storm');
define('STORM_LOG','Storm log');
define('MAP_DIRECTIONS','Directions');
define('SCOUT_INFO','Scout\'s info');
define('DESERT','Desert');
define('M_BUILDING_REGENERATED','Building <strong>regenerated</strong>');
define('M_ZONE_REGENERATED','Zone <strong>regenerated</strong>');
define('M_BUILDING_DEPLETED','Building <strong>depleted</strong>');
define('M_ZONE_DEPLETED','Zone <strong>depleted</strong>');
define('M_ZONE_DIG','debris: <strong>%d</strong>');

# travel
define('Ngo','NORTH (top)');
define('Wgo','WEST (left)');
define('Sgo','SOUTH (bottom)');
define('Ego','EAST (right)');
define('TRAVEL_TITLE','Travel Agency');
define('TRAVEL_INFO','');
define('TRAVEL_YOUR_GROUP','Your travel group');
define('TRAVEL_NO_GROUP','You are not a member of a travel group. Just create one yourself!');
define('TRAVEL_GROUP_NAME','Group name');
define('TRAVEL_NEW_GROUP_NAME','s travel group');
define('TRAVEL_GROUP_PERSISTENT','Make group persistent');
define('TRAVEL_GROUP_ROUTE','Expedition');
define('TRAVEL_GROUP_CREATE','Create group');
define('TRAVEL_GROUP_NO_MEMBERS','Please name your group members');
define('TRAVEL_GROUP_MEMBERS','Participants');
define('TRAVEL_GROUP_UPDATE','Update group');
define('TRAVEL_GROUP_LEAVE','Leave group');
define('TRAVEL_GROUP_CLOSE','Close group');
define('TRAVEL_YOUR_LOCATION','Current location');
define('TRAVEL_ROUTE_PROGRESS','That\'s zone #%n on your route (%p% done).');
define('TRAVEL_ROUTE_AWAY','You left the pre-defined route.');
define('TRAVEL_ROUTE_NEXT','Next zone is to the <span style="font-weight:bold;color:#090;">%s</span>.');
define('TRAVEL_ROUTE_MAX_ZOMBIES','Along the route you will encounter up to <span style="font-weight:bold;color:#f00;">%d zombies</span>.');
define('TRAVEL_ROUTE_ITEMS','These objects are on you route');
define('TRAVEL_ALL_GROUPS','All groups travelling today');
define('TRAVEL_CHAOS','Chaos. Nobody is here. Maybe you should leave too?');

# radar
define('RADAR_ERROR','An error occured. Data has not been saved.');
define('RADAR_BANNED','Data seems not reliable and has not been saved.');
define('RADAR_SCOUT','Zombie figures have been saved. Well done, scout!');
define('RADAR_SCAVENGER','Replenishing states have been saved. Scavenger FTW!');
define('RADAR_GUARDIAN','Don\'t touch the machine, guard something.');
define('RADAR_CITIZEN','Leave the radar system alone. Heroes only!');
define('RADAR_HUNTER','You\'ve got a survival book, not a manual, right?');
define('RADAR_TAMER','Did your dog just pee on the buttons? Eeeew.');

# stats
define('STAT_ZOMBIE_TITLE','Zombie attacks');
define('STATS_DEFOE5','Season 5');
define('STATS_HARD5','Season 5 Hardcore');
define('STATS_DEFOE4','Season 4');
define('STATS_HARD4','Season 4 Hardcore');
define('STATS_DEFOE3','Season 3');
define('STATS_DEFOE2','Season 2');
define('STAT_SOULS_TITLE','Soul points');
define('STAT_REWARDS_TITLE','Distinctions');
define('STAT_TITLES_TITLE','Titles');
define('STAT_CC_TITLE','Compare citizens');
define('STAT_ACTIVETOWNS_TITLE','Active towns');
define('STAT_OLDTOWNS_TITLE','Old towns');
define('STAT_SCOUTS_TITLE','Scouts');
define('STAT_ZOMBIE_INFO','');
define('STAT_ZOMBIE_BASE','Zombie attacks - %d data sets from %s towns');
define('DEATH_CALC','Death calculator <em>by haase</em>');
define('DEATH_CALC_ZOMBIES','zombies get in');
define('DEATH_CALC_CITIZENS','citizens in town');
define('DEATH_CALC_PERSDEF','personal defense');
define('DEATH_CALCULATE','What are my chances?');
define('COMPARE','Compare');
define('MIN','Minimum');
define('MAX','Maximum');
define('AVG','Average');
define('MED','Median');
define('COUNT_DATASETS','# of data sets');
define('YOUR_CITY','Your town');
define('GOOD_LUCK','Good luck!');
define('STAT_ACTIVETOWNS_INFO','');
define('STAT_OLDTOWNS_INFO','');
define('STAT_CITY_NAME','Name of town');
define('STAT_LAST_DAY','Survived days');
define('STAT_CHAOS','Chaos');
define('STAT_DEVAST','Devastated');
define('STAT_CHAOS_X','Chaos!');
define('STAT_DEVAST_X','Town gates destroyed!');
define('STAT_SURVIVORS','Survivors');
define('STAT_WATER_WELL','Water in well');
define('STAT_WATER_BANK','Water in bank');
define('STAT_JERRY_BANK','Jerry cans in bank');
define('STAT_DEF_ITEMS','Number of defensive objects');
define('STAT_LAST_ZOMBIES','Number of zombies last night');
define('STAT_LAST_DEF','Town defense last night');
define('STAT_LAST_UPDATE','Last update');
define('ZOMBIE_SPREAD','Zombie attacks - day %d | season %s');
define('OBTAINABLE','Obtainable for');
define('OGAME','This calculator is for Die2Nite, not OGame. There can only be 40 residents in a town.');
define('YOU_WILL_SURVIVE','You will survive this attack with<br/>a probability of');
define('SHOW_ONLY_OWN_TOWNS','Only show my towns');
define('SHOW_ONLY_TOWNS_WITH','Only show towns with at least');
define('SHOW_DEFOE_TOWNS','Show normal towns');
define('SHOW_HARD_TOWNS','Show hardcore towns');
define('SHOW_INTERPOLATED_TOWNS','Toggle towns that have or have not been updated today');
define('STAT_MAP_SIZE','Map size');
define('SURVIVORS','Survivors');
define('BUILDINGS','Buildings');
define('DEFENSIVE_OBJECTS','Defensive items');
define('TOWN_DEFENSE','Town defense');
define('TOWN_DEF_BASE','Town base defense');
define('TOWN_DEF_BUILDINGS','Town defense from constructions');
define('TOWN_DEF_HOMES','Town defense from citizens\' homes');
define('TOWN_DEF_GUARDS','Town defense from Guardians');
define('TOWN_DEF_ITEMS','Town defense from defensive items');
define('TOWN_DEF_UPGRADES','Town defense from upgrades');
define('MAP','Map');
define('ATTACKS','Attacks');
define('CADAVER','Cadaver');
define('LAST_ATTACK','Yesterday\'s attack');
define('NEXT_ATTACK','Today\'s attack');
define('REWARDS','Rewards');
define('TITLES','Titles');
define('SOUL_POINTS', 'Soul points');
define('POINTS', 'Points');
define('PROVIANT', 'Water &amp; food');
define('GAMES', 'Town history');
define('NO_DATA_AVAILABLE', 'No data available.');
define('RANKINGPOINTS', 'Current ranking points: %r survivors and %d dead. These figures may be inaccurate!');

# toolbox
define('ADD','Add');
define('SAVE','Save');
define('EXPLORATION_LEVEL','Exploration level');
